- name: Ensure WireGuard config directory exists
  file:
    path: "{{ wg_config_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate WireGuard private key
  command: wg genkey
  register: private_key

- name: Generate WireGuard public key
  command: echo "{{ private_key.stdout }}" | wg pubkey
  register: public_key

- name: Generate a random port for WireGuard
  shell: echo $((RANDOM % ({{ wg_port_range_end }} - {{ wg_port_range_start }} + 1) + {{ wg_port_range_start }}))
  register: random_port

- name: Save WireGuard configuration without peer details
  template:
    src: wireguard.env.j2
    dest: "{{ wg_config_path }}/wg0.conf"
    owner: root
    group: root
    mode: '0600'

- name: Save port information
  copy:
    content: "{{ random_port.stdout }}"
    dest: "{{ wg_config_path }}/wg.port"
    owner: root
    group: root
    mode: '0600'
