---
- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: Deploy Docker Compose for Node.js and WireGuard
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /home/ubuntu/updated_node/docker_node/docker-compose.yml

- name: Start Docker Compose
  ansible.builtin.command:
    cmd: docker-compose up -d
    chdir: /home/ubuntu/updated_node/docker_node/
