- name: Install required packages
  apt:
    name:
      - docker.io
      - wireguard
    state: present
    update_cache: yes

- name: Ensure Docker is started
  service:
    name: docker
    state: started
    enabled: true

- name: Build the node_wireguard Docker image
  docker_image:
    name: node_wireguard
    tag: latest
    source: build
    build:
      path: /home/ubuntu/updated_node/docker_node
  register: build_result

- name: Create the Docker network for WireGuard
  docker_network:
    name: wg-network
    state: present

- name: Run Redis container
  docker_container:
    name: redis
    image: redis:latest
    state: started
    restart_policy: always
    networks:
      - name: wg-network

- name: Run Node.js container for WireGuard
  docker_container:
    name: node_wireguard
    image: node_wireguard:latest
    state: started
    restart_policy: always
    ports:
      - "{{ random_port }}:{{ random_port }}"
    volumes:
      - "{{ wg_config_path }}:/etc/wireguard"
    privileged: true
    networks:
      - name: wg-network
    env:
      ISANSIBLE: "true"
      ADDRESS: "10.0.0.0"
      PORT: "8000"
      REDIS_URL: "redis://redis:6379"
    # Make sure permissions are correct on the mounted config file
    command: >
      bash -c "chown -R 1000:1000 /etc/wireguard && node /home/ubuntu/updated_node/docker_node/src/index.ts"  # Adjust the path
    # You can also specify the user running the container if needed
    user: "1000"  # This is the UID of the user that should have permissions to access the config file

- name: Ensure correct file permissions on config file
  file:
    path: "{{ wg_config_path }}"
    owner: "1000"
    group: "1000"
    mode: "0644"
