- name: Install required packages
  apt:
    name:
      - docker.io
      - wireguard
    state: present
    update_cache: yes

- name: Ensure Docker is started
  service:
    name: docker
    state: started
    enabled: true

- name: Build the node_wireguard Docker image
  docker_image:
    name: node_wireguard
    tag: latest
    source: build
    build:
      path: /home/ubuntu/updated_node/docker_node
  register: build_result

- name: Create the Docker network for WireGuard
  docker_network:
    name: wg-network
    state: present

- name: Run Node.js container for WireGuard
  docker_container:
    name: node_wireguard
    image: node_wireguard:latest
    state: started
    restart_policy: always
    ports:
      - "{{ random_port }}:{{ random_port }}"
    volumes:
      - "{{ wg_config_path }}:/etc/wireguard"
    privileged: true
    cap_add:
      - NET_ADMIN
    networks:
      - wg-network
    environment:
      - PORT=8000
      - ADDRESS=10.8.0.0
      - ISANSIBLE=true
      - REDIS_URL=redis://redis:6379